# GoReleaser configuration for Goatway
# Documentation: https://goreleaser.com
version: 2
project_name: goatway

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: goatway
    binary: goatway
    main: ./cmd/api
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.BuildTime={{.CommitDate}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^.*feat.*:+.*$"
    - title: Bug Fixes
      regexp: "^.*fix.*:+.*$"
    - title: Refactoring
      regexp: "^.*refactor.*:+.*$"

release:
  github:
    owner: mandalnilabja
    name: goatway
  draft: false
  prerelease: auto
  name_template: "Goatway v{{.Version}}"
