# GoReleaser configuration for Goatway
# Documentation: https://goreleaser.com
version: 2
project_name: goatway

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod verify

builds:
  - id: goatway
    binary: goatway
    main: ./cmd/api
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.BuildTime={{.CommitDate}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^.*feat.*:+.*$"
    - title: Bug Fixes
      regexp: "^.*fix.*:+.*$"
    - title: Refactoring
      regexp: "^.*refactor.*:+.*$"

homebrew_casks:
  - repository:
      owner: mandalnilabja
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/mandalnilabja/goatway"
    description: "Lightweight, streaming-safe, OpenAI-compatible HTTP proxy for LLM providers"
    caveats: |
      If macOS shows 'goatway is damaged', run:
        xattr -dr com.apple.quarantine $(which goatway)
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goatway"]
          end

release:
  github:
    owner: mandalnilabja
    name: goatway
  draft: false
  prerelease: auto
  name_template: "Goatway v{{.Version}}"
